# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ruby Developer
email:
# description: >- # this means to ignore newlines until "baseurl:"
#   This is personal page of se vik
#   And this is fine!
domain: vikkanaev.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://vikkanaev.github.io  # the base hostname and protocol for your site, e.g. http://example.com
# baseurl:       # place folder name if the site is served in a subfolder

# Build settings
# theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge

author:
  name   : "Victor Kanaev"
  avatar : '/assets/images/bio-photo.jpg'
  # bio    : >-
  #   My awesome biography constrained to a sentence or two goes here.
  #   But I can make new line
  links:
    - label: "Website!"
      icon: "fas fa-fw fa-link"
      url: "https://vikkanaev.github.io/"
    - label: "VikKanaev"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/VikKanaev"
    - label: "Kanaevv"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kanaevv/"
    - label: "vikkanaev"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vikkanaev/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/VikKanaev"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kanaevv/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vikkanaev/"

defaults:
#   # _posts
#   - scope:
#       path: ""
#       type: posts
#     values:
#       layout: single
#       author_profile: true
#       read_time: true
#       comments: true
#       share: true
#       related: true
#   # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
